defmodule :"Elixir.OpenBudget.Repo.Migrations.User budget relationship" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bank_accounts) do
      modify :balance, :decimal, default: 0
    end
  end

  def down do
    alter table(:bank_accounts) do
      modify :balance, :decimal, default: nil
    end
  end
end