defmodule OpenBudget.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transactions) do
      add :pending, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:transactions) do
      remove :pending
    end
  end
end