defmodule :"Elixir.OpenBudget.Repo.Migrations.Add active column to budget" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:budgets) do
      add :active, :boolean, null: false, default: false
    end

    create table(:bank_accounts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :balance, :decimal, null: false

      add :budget_id,
          references(:budgets,
            column: :id,
            name: "bank_accounts_budget_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:bank_accounts, "bank_accounts_budget_id_fkey")

    drop table(:bank_accounts)

    alter table(:budgets) do
      remove :active
    end
  end
end