defmodule OpenBudget.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :assigned_limit, :decimal, null: false, default: 0.0
      add :activity, :decimal, null: false, default: 0.0
      add :parent_id, :uuid

      add :budget_id,
          references(:budgets,
            column: :id,
            name: "categories_budget_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:categories, "categories_budget_id_fkey")

    drop table(:categories)
  end
end