defmodule :"Elixir.OpenBudget.Repo.Migrations.Add transactions" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text, null: false
      add :amount, :decimal, null: false, default: 0

      add :bank_account_id,
          references(:bank_accounts,
            column: :id,
            name: "transactions_bank_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:transactions, "transactions_bank_account_id_fkey")

    drop table(:transactions)
  end
end